# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        factual inconsistency: 5
        factual inaccuracies: 5
        hallucinations: 5
        kaggle: 3
        resnet: 3
        anomaly detection: 1

# 通知の閾値
score_threshold: 0
